# Generated by Django 3.1.7 on 2021-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Waiting'), ('ACCP', 'Accepted\t'), ('DECL', 'Declined')], default='WAIT', max_length=10),
        ),
    ]
