# Generated by Django 3.1.7 on 2021-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Waiting'), ('ACCP', 'Accepted'), ('DECL', 'Declined')], default='WAIT', max_length=10),
        ),
    ]
