# Generated by Django 3.1.7 on 2021-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('hairdr_id', models.IntegerField()),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
            ],
        ),
    ]
