# Generated by Django 3.1.7 on 2021-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210531_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Waiting', 'WAIT'), ('Accepted', 'ACCP'), ('Declined', 'DECL')], default='WAIT', max_length=10),
        ),
    ]
