# Generated by Django 3.1.7 on 2021-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
