# Generated by Django 3.1.7 on 2021-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210414_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
