# Generated by Django 3.1.7 on 2021-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_hairdresser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='test',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
