# Generated by Django 3.1.7 on 2021-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210528_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='location',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
