# Generated by Django 3.1.7 on 2021-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdresser',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='startHour',
            field=models.TimeField(null=True),
        ),
    ]
