# Generated by Django 3.1.7 on 2021-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210528_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='endHour',
            field=models.TimeField(null=True),
        ),
    ]
