# Generated by Django 3.1.7 on 2021-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_hairdresser_endhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
